[libraries]
androidGradlePlugin = "com.android.tools.build:gradle:8.6.0"
test-junit = "org.junit.jupiter:junit-jupiter:5.11.0"
test-strikt = "io.strikt:strikt-core:0.35.1"

[plugins]
kotlin = "org.jetbrains.kotlin.jvm:2.0.20"
dokka = "org.jetbrains.dokka:1.9.20"
