[libraries]
androidGradlePlugin = "com.android.tools.build:gradle:8.1.2"
test-junit = "org.junit.jupiter:junit-jupiter:5.10.1"
test-strikt = "io.strikt:strikt-core:0.34.1"

[plugins]
kotlin = "org.jetbrains.kotlin.jvm:1.9.20"
